version: '3.9'

services:
  frontend_app:
    build:
      dockerfile: Dockerfile
      context: frontend
    container_name: frontend_app
    env_file:
      - .env
    depends_on:
      - mongo_database
      - backend_app
    ports:
      - "${FRONTEND_PORT}:80"

  backend_app:
    container_name: backend_app
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: backend
    networks:
      - mongo_database
    depends_on:
      - mongo_database
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  mongo_database:
    image: mongo:latest
    container_name: mongo_database
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    networks:
      - mongo_database

networks:
  mongo_database: { }